<a href="https://colab.research.google.com/github/VoTanThinh/ANN/blob/main/ANN(mangthankinhnhantao).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron
x=[[0,0],[0,1],[1,0],[1,1]]
t=[0,1,1,1]
model = Perceptron()                #dạy học
model.fit(x,t)
model.score(x,t)

1.0

In [ ]:
x1=[[-3,-3],[1,1],[13,18],[15,12]]
y1=model.predict(x1)
model.score(x1,y1)
print((y1))

[0 1 1 1]

In [ ]:
from sklearn.linear_model import Perceptron
x1=[[0.5,0.5],[-0.5,0.5],[10,20],[-1,-2]]
y1=model.predict(x1)
model.score(x1,y1)
print(y1)

[1 1 1 0]

In [ ]:
x1=[[-0.5,0.5]]             # dưới 0.5 là 0 và trên 0.5 là 1 đường phân chia đường dữ liệu
y1=model.predict(x1)
model.score(x1,y1)
print((y1))

[1]

In [ ]:
from sklearn.linear_model import Perceptron
x2=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
t2=[1,1,0,0]
model = Perceptron()
model.fit(x2,t2)
model.score(x2,t2)

x3=[[0,0],[0,1],[1,0],[1,1]]            # dưới 0.5 là 0 và trên 0.5 là 1 đường phân chia đường dữ liệu
y4=model.predict(x3)
model.score(x3,y4)
print((y4))

[0 0 0 0]

In [ ]:
from pandas.io.formats.format import east_asian_width
# truy xuất tập dữ liệu trên mạng phân loại hoa lan (0,1,2) xem (0,1)                #3 loại 
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split          #dữ liệu train k được dùng để test
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler              #sacle tỉ về cho dữ liệu đều nhau
iris = datasets.load_iris()                 #lấy thông tin từ dữ liệu data của hoa lan   #(150 hàng 4 cột)
x=iris.data                                 
y=iris.target                               
print(x[:5])                            #in ra dữ diệu cần tìm trong khoảng
print(y[:5])

#chia dữ liệu
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)                          #30% test 70%train
sc = StandardScaler()
sc.fit(x_train)    # học tỉ lệ
x_train_std = sc.transform(x_train)     # nhân tỉ lệ đó 
x_test_std = sc.transform(x_test)
print(x_train_std[:5],x_train[:5])   #xuất 2 dữ liệu ra
print(y[:5])
model2 = Perceptron(max_iter=90,eta0=0.9,random_state=0)    #(số lần học max_iter=40laan, eta0(tốc độ học (0-1)),radom_state trạng thái lấy)
model2.fit(x_train_std,y_train)   #
y_pred = model2.predict(x_test_std)   # tien đón giá trị ra
print(y_pred)
print(y_test)
print('độ chính xác mô hình',accuracy_score(y_test,y_pred))  #in ra độ chính xác                                    #sacle thì tỉ lệ tăng lên

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[-1.7982198   0.33719641 -1.40100669 -1.31678927]
 [-1.0409481  -0.13175224 -1.2286172  -1.31678927]
 [-1.7982198  -0.13175224 -1.40100669 -1.31678927]
 [ 0.47359532 -0.36622656  0.32288826  0.14420171]
 [-0.91473614  1.74404235 -1.2286172  -1.31678927]] [[4.4 3.2 1.3 0.2]
 [5.  3.  1.6 0.2]
 [4.4 3.  1.3 0.2]
 [6.2 2.9 4.3 1.3]
 [5.1 3.8 1.6 0.2]]
[0 0 0 0 0]
[2 1 1 0 1 1 1 2 1 0 0 0 1 1 1 0 0 0 1 0 2 0 2 1 1 1 2 1 2 0 2 2 0 2 2 1 2
 0 0 2 2 2 1 0 2]
[2 1 1 0 1 1 2 2 1 0 0 0 1 1 1 0 0 0 2 0 2 0 2 1 1 1 2 1 2 0 2 1 0 2 2 1 2
 0 0 2 2 2 1 0 2]
độ chính xác mô hình 0.9333333333333333

In [ ]:
import pandas as pd        #INPUT:LOÀI+CÁC ĐẶC TÍNH
import numpy as np         #OUTPU:GIỚI TÍNH
from pandas.io.formats.format import east_asian_width
# truy xuất tập dữ liệu trên mạng phân loại hoa lan (0,1,2) xem (0,1)                #3 loại 
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split          #dữ liệu train k được dùng để test
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler 
url='crabs.csv'
data= pd.read_csv(url)
x = data['speies']                                 
y = data['sex'] 
k=data.replace(['B','O'],['0','1'])
k.head(20)
z=data.replace(['M','F'],['1','0'])
z.head(20)

   speies sex  index  fontallip  rearwidth  length  width  depth
0       0   M      1        8.1        6.7    16.1   19.0    7.0
1       0   M      2        8.8        7.7    18.1   20.8    7.4
2       0   M      3        9.2        7.8    19.0   22.4    7.7
3       0   M      4        9.6        7.9    20.1   23.1    8.2
4       0   M      5        9.8        8.0    20.3   23.0    8.2
5       0   M      6       10.8        9.0    23.0   26.5    9.8
6       0   M      7       11.1        9.9    23.8   27.1    9.8
7       0   M      8       11.6        9.1    24.5   28.4   10.4
8       0   M      9       11.8        9.6    24.2   27.8    9.7
9       0   M     10       11.8       10.5    25.2   29.3   10.3
10      0   M     11       12.2       10.8    27.3   31.6   10.9
11      0   M     12       12.3       11.0    26.8   31.5   11.4
12      0   M     13       12.6       10.0    27.7   31.7   11.4
13      0   M     14       12.8       10.2    27.2   31.8   10.9
14      0   M     15       12.8       10.9    27.4   31.5   11.0
15      0   M     16       12.9       11.0    26.8   30.9   11.4
16      0   M     17       13.1       10.6    28.2   32.3   11.0
17      0   M     18       13.1       10.9    28.3   32.4   11.2
18      0   M     19       13.3       11.1    27.8   32.3   11.3
19      0   M     20       13.9       11.1    29.2   33.3   12.1